---
title: "About Me"
output: html_document
---

I am currently a PhD Candidate in the Department of Marine and Environmental Sciences at Northeastern University's [Marine Science Center](https://cos.northeastern.edu/marinescience/). I am advised by Dr. Steven Scyphers in the [Social-Ecological Sustainability Lab](https://www.scypherslab.com/). I am also a Visiting PhD Student at the University of South Alabama and the Dauphin Island Sea Lab.

My research focuses on engaging community/local experts using participatory approaches and applying statistical and computational methods to better understand social-ecological problems.  My work is interdisciplinary and spans social and environmental sciences geared to practically benefit coastal ecosystems and societies.

Previously, I received my Bachelor of Science in Environmental Sciences at the University of North Carolina at Chapel Hill. I also worked at UNC-CH's [Institute of Marine Sciences](https://ims.unc.edu/) as a research technician in the Estuarine Ecology Lab. 