---
title: "Publications"
output: html_document
---

<span style="font-size: 18px;">**Peer-Reviewed:**</span>  

8\. Alemu I, J.B., Hughes, A.R., Osland, M.J., **Swinea, S.H.**, Thorne, K.A., Bardou, R., Shepard, C.C., & Scyphers, S.B. Socio-cultural perceptions and stated preferences for climate adaptation: Insights from coastal property owners in the northern Gulf of Mexico. *People and Nature*. [https://doi.org/10.1002/pan3.10794](https://doi.org/10.1002/pan3.10794)

7\. **Swinea, S.H.**, Hughes, A.R., Osland, M.J., Shepard, C.C., Thorne, K.B., Alemu I, J.B., Bardou, R., and Scyphers, S.B. 2024. Marshes to mangroves: Residential surveys reveal perceived wetland trade-offs for ecosystem services. *Landscape and Urban Planning*. [https://doi.org/10.1016/j.landurbplan.2024.105203](https://doi.org/10.1016/j.landurbplan.2024.105203)

6\. Bardou, R., Osland, M.J., Alemu I, J.B., Feher, L.C., Harlan, D., Scyphers, S., Shepard, C.C., **Swinea, S.H.**, Thorne, K., Andrew, J.E., & Hughes, A.R. 2024. Projected changes in mangrove distribution and vegetation structure under climate change in the southeastern United States. *Journal of Biogeography*. [https://doi.org/10.1111/jbi.14985](https://doi.org/10.1111/jbi.14985)

5\. Prasky, E.G., Drymon, J.M., Karnauskas, M., Anderson, A.Q., Gibbs, S.L., Grabowski, J.H., Jargowsky, A.E., McAree, D.M., Osowski, A.R., **Swinea, S.H.**, and Scyphers, S.B. 2023. Depredation influences anglers’ perceptions on coastal shark management and conservation in the United States Gulf of Mexico. *Frontiers in Conservation Science*. [https://doi.org/10.3389/fcosc.2023.1271223](https://doi.org/10.3389/fcosc.2023.1271223)

4\. Bardou, R., Osland, M.J., Scyphers, S., Shepard, C., Aerni, K.E., Alemu I, J.B., Crimian, R., Day, R.H., Enwright, N.M., Feher, L.C., Gibbs, S.L., O’Donnell, K., **Swinea, S.H.**, … and Hughes, A.R. 2023. Rapidly changing range limits in a warming world: critical data limitations and knowledge gaps for advancing understanding of mangrove range dynamics in the southeastern USA. *Estuaries and Coasts*. [https://doi.org/10.1007/s12237-023-01209-7](https://doi.org/10.1007/s12237-023-01209-7)

3\. Zhang, Y.S., **Swinea, S.H.**, Roskar, G., Trackenberg, S.N., Gittman, R.K., Jarvis, J.C., Kenworthy, W.J., Yeager, L.A., and Fodrie, F.J. 2022. Tropical cyclone impacts on seagrass-associated fishes in a temperate/subtropical estuary. *PLoS ONE*. [https://doi.org/10.1371/journal.pone.0273556](https://doi.org/10.1371/journal.pone.0273556)

2\. Osland, M.J., Hughes, A.R., Armitage, A.R., Scyphers, S.B., Cebrian, J., **Swinea, S.H.*,** Shepard, C.C., Allen, M.S., Feher, L.C., … and Bardou, R. 2022. The impacts of mangrove range expansion on wetland ecosystem services in the southeastern United States: current understanding, knowledge gaps, and emerging research needs. *Global Change Biology*. [https://doi.org/10.1111/gcb.16111](https://doi.org/10.1111/gcb.16111)

1\. **Swinea, S.H.** and Fodrie, F.J. 2021. Gulf fisheries supported resilience in the decade following unparalleled oiling. *Ecosphere*. [https://doi.org/10.1002/ecs2.3801](https://doi.org/10.1002/ecs2.3801)

<span style="font-size: 18px;">**Non-Peer Reviewed:**</span> 

2\. Drymon, J.M., Osowski, A., Jefferson, A., Anderson, A., McAree D., Scyphers, S.B., Prasky, E., **Swinea, S.H.**, Gibbs, S., Karnauskas, M., and Gervasi, C. 2022. Co-producing a shared characterization of depredation in the Gulf of Mexico reef fish fishery: 2022 Workshop summary report. Southeast Data, Assessment & Review (SEDAR). [https://sedarweb.org/documents/sedar-74-dw-32-co-producing-a-shared-characterization-of-depredation-in-the-gulf-of-mexico-reef-fish-fishery-2022-workshop-summary-report/](https://sedarweb.org/documents/sedar-74-dw-32-co-producing-a-shared-characterization-of-depredation-in-the-gulf-of-mexico-reef-fish-fishery-2022-workshop-summary-report/) 

1\. Scyphers, S.B., **Swinea, S.H.**, Gibbs, S., and Heyman, W. 2021. Stakeholder assessment and concept mapping in support of Fishery Ecosystem Planning for the Gulf of Mexico: Summary project report. Gulf of Mexico Fishery Management Council Contract Award No. NA15NMF4410011. [https://gulfcouncil.org/wp-content/uploads/03e.-Q-4d-121021_FEP-Stakeholder-Assessment-_-Modeling-Summary-Report_v4.pdf](https://gulfcouncil.org/wp-content/uploads/03e.-Q-4d-121021_FEP-Stakeholder-Assessment-_-Modeling-Summary-Report_v4.pdf)
