---
title: "Research"
output: html_document
---

<span style="font-size: 18px;">**Marshes to mangroves: Social and ecological implications of mangrove expansion**</span>  


Tropical species are expanding their range into temperate ecosystems globally, with uncertain impacts on ecosystem services and societies. In the US Gulf of Mexico, tropical mangroves are beginning to outcompete temperate salt marshes. How do coastal residents perceive this change?  We surveyed waterfront homeowners in mangrove expansion hotspots and asked them if mangroves or marshes were better at supporting coastal fisheries. Our ordinal logistic regression had a surprising result: revealed people who had marshes on their shoreline actually perceived that mangroves were better at supporting coastal fisheries. This highlights the importance of soliciting the perceptions and knowledge of local people, rather than assuming their perceptions might be driven by environmental conditions alone.

This work resulted from a collaborative, interdisciplinary effort between academic, federal, and nonprofit partners. Check out our [Mangrove Explorer](https://maps.coastalresilience.org/mangrove-explorer/), where users can explore ecological and social dynamics of mangrove expansion, as well as other recent publications.

Related publication:
**Swinea, S.H.**, Hughes, A.R., Osland, M.J., Shepard, C.C., Thorne, K.B., Alemu I, J.B., Bardou, R., and Scyphers, S.B. 2024. Marshes to mangroves: Residential surveys reveal perceived wetland trade-offs for ecosystem services. *Landscape and Urban Planning*. [https://doi.org/10.1016/j.landurbplan.2024.105203](https://doi.org/10.1016/j.landurbplan.2024.105203)

<span style="font-size: 18px;">**Fisheries resilience to an environmental disaster**</span> 

The *Deepwater Horizon* oil spill in April 2010 was the most costly environmental disaster in United States history. Millions of barrels of oil were dispersed throughout the Gulf of Mexico, causing concern over the health of marine fauna and seafood safety. Projections estimated that Gulf of Mexico fisheries would lose billions in the years following the spill, but did this economic loss come to pass? We compiled state and regional data for commercial, recreational, and mariculture fishing industries to examine pre- and post-spill trends, and demonstrated that these fishery sectors showed remarkable resilience to unparalleled oiling. Economic trends were stable or improved following the spill, and shifts in harvest could not explain these trends. These social–ecological dynamics likely aided recovery of stressed coastal GOM communities in the years after *DwH*, although increased fishing pressure in the post-spill era may have consequences for future GOM ecosystem structure, function, and resilience.

Related publication:
**Swinea, S.H.** and Fodrie, F.J. 2021. Gulf fisheries supported resilience in the decade following unparalleled oiling. *Ecosphere*. [https://doi.org/10.1002/ecs2.3801](https://doi.org/10.1002/ecs2.3801)

